'use client'
import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '@/components/ui/button'
import { Slider } from '@/components/ui/slider'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
type Entry={id:string;passageId:string;documentId:string;name:string;locator:string;title:string;quote:string;eventDate:string|null;precision:string;status:string;evidenceType:string;note:string;revision:number;superseded:boolean}
type Doc={id:string;name:string;hash:string;status:string;warnings:string[];importedAt:string;parentId:string|null;supersedesId:string|null;sourceUrl:string|null;publicationDate:string|null}
type Hit={id:string;caseId:string;documentId:string;name:string;caseTitle:string;locator:string;text:string}
type Revision={revision:number;title:string;quote:string;eventDate:string|null;precision:string;status:string;note:string;createdAt:string;reviewedBy:string|null}
const field='block w-full rounded border border-input bg-background p-2 text-sm'
async function read(url:string,init:RequestInit={}) {
  const response=await fetch(url,{...init,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...init.headers}})
  if(!response.ok){let msg='Request failed';try{const data=await response.json();if(typeof data.error==='string')msg=data.error}catch{}throw new Error(msg)}
  return response
}
const textError=(e:unknown)=>e instanceof Error?e.message:'Request failed'
function toBase64(bytes:ArrayBuffer){let raw='';const values=new Uint8Array(bytes);for(let i=0;i<values.length;i+=8192)raw+=String.fromCharCode(...values.subarray(i,i+8192));return btoa(raw)}
export function CaseEvidence({workspaceId,caseId,onSelectCase,reportTitle,externalRevision,onChanged}:{workspaceId:string;caseId:string;onSelectCase:(id:string)=>void;reportTitle?:string;externalRevision?:number;onChanged?:()=>void}) {
  const endpoint=`/api/workspaces/${encodeURIComponent(workspaceId)}/cases/${encodeURIComponent(caseId)}/evidence`
  const [docs,setDocs]=useState<Doc[]>([]),[events,setEvents]=useState<Entry[]>([]),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
  const [sourceUrl,setSourceUrl]=useState(''),[publicationDate,setPublicationDate]=useState(''),[supersedesId,setSupersedesId]=useState(''),[filter,setFilter]=useState('DRAFT'),[limit,setLimit]=useState(10000)
  const [q,setQ]=useState(''),[earlier,setEarlier]=useState(false),[hits,setHits]=useState<Hit[]>([]),[exportId,setExportId]=useState('')
  useEffect(()=>{const controller=new AbortController();setLoading(true);setLoadError('');read(endpoint,{signal:controller.signal}).then(r=>r.json()).then(data=>{if(!controller.signal.aborted){setDocs(data.documents);setEvents(data.events)}}).catch(e=>{if(!controller.signal.aborted)setLoadError(textError(e))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[endpoint,revision,externalRevision])
  async function action(input:Record<string,unknown>){return (await read(endpoint,{method:'POST',body:JSON.stringify(input)})).json()}
  async function importFiles(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const files=(form.elements.namedItem('files') as HTMLInputElement).files;if(!files?.length)return;setBusy(true);setError('');setNotice('');let imported=0
    try{if(files.length>5)throw new Error('Import up to five files per batch.');if(supersedesId&&files.length>1)throw new Error('Select one file when recording an amendment.');for(const file of Array.from(files)){if(file.size>5*1024*1024)throw new Error(`${file.name}: maximum 5 MiB`);setNotice(`Scanning and extracting ${file.name}…`);const result=await action({action:'import',name:file.name,bytes:toBase64(await file.arrayBuffer()),sourceUrl:sourceUrl||undefined,publicationDate:publicationDate||undefined,supersedesId:supersedesId||undefined});imported++;setNotice(result.duplicate?'Existing identical document reused.':`${imported} file(s) imported. Extracted entries need review.`)}form.reset();setSupersedesId('')}
    catch(e){setNotice('');setError(`${textError(e)} ${imported} file(s) completed before this error.`)}finally{(form.elements.namedItem('files') as HTMLInputElement).value='';setBusy(false);setRevision(x=>x+1);onChanged?.()}}
  async function search(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setHits([]);try{const data=await (await read(`${endpoint}?action=search&q=${encodeURIComponent(q)}&earlier=${earlier}`)).json();setHits(data.results);setNotice(`${data.results.length} result(s). Exact text search—not semantic verification.`)}catch(e){setError(textError(e))}finally{setBusy(false)}}
  async function download(url:string,name:string){setError('');try{const blob=await (await read(url)).blob();const object=URL.createObjectURL(blob),a=document.createElement('a');a.href=object;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(object),1000)}catch(e){setError(textError(e))}}
  async function produce(){setBusy(true);setError('');try{const result=await action({action:'export',...(reportTitle?{reportTitle}:{})});setExportId(result.id);setNotice('Reviewed PDF and source manifest retained. Download requires current case permissions.')}catch(e){setError(textError(e))}finally{setBusy(false)}}
  const filtered=events.filter(e=>filter==='ALL'||e.status===filter)
  return <section className="mt-6 border-t pt-6 space-y-5" aria-label="Private case evidence">
    <div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-semibold">Evidence & timeline</h3><p className="text-sm text-muted-foreground">Keep the source. Review the event. See what changed.</p></div><Button variant="outline" onClick={()=>setRevision(x=>x+1)} disabled={busy||loading}>Refresh evidence</Button></div>
    {error&&<p role="alert" className="rounded border border-destructive p-3 text-sm">{error}</p>}{notice&&<p role="status" className="rounded bg-secondary p-3 text-sm">{notice}</p>}
    {loadError&&<p role="alert" className="rounded border border-destructive p-3 text-sm">Could not refresh evidence: {loadError}</p>}
    {loading?<p role="status">Loading evidence…</p>:<>
    <Tabs defaultValue="timeline"><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="timeline">Timeline ({events.length})</TabsTrigger><TabsTrigger value="sources">Sources ({docs.length})</TabsTrigger><TabsTrigger value="import">Import</TabsTrigger><TabsTrigger value="search">Find / earlier cases</TabsTrigger><TabsTrigger value="export">Export</TabsTrigger></TabsList>
    <TabsContent value="import"><form className="space-y-4 pt-3" onSubmit={importFiles}>
      <p className="text-sm">Import only material you are authorised to hold. Originals stay private; no document content is sent to an AI or external parser. Do not upload identifiable child material.</p>
      <label className="block text-sm">Files<input name="files" type="file" className={field} accept=".pdf,.docx,.eml,.txt,.csv,.png,.jpg,.jpeg,.mp3,.wav" multiple required disabled={busy}/></label>
      <p className="text-sm text-muted-foreground">Drop anything: PDF, DOCX, EML, TXT/CSV text notes, PNG/JPEG images, or MP3/WAV audio. Five files per batch, 5 MiB each; 100 documents / 50 MiB per case. Images, scanned PDFs and audio are retained as originals but are not auto-transcribed — add a text note with the relevant quote for the timeline. An unsupported email attachment rejects that email import.</p>
      <label className="block text-sm">Source URL, if known<input type="url" className={field} value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://…"/></label><p className="text-sm text-muted-foreground">This records a reference only; it does not fetch or verify the website.</p>
      <label className="block text-sm">Publication date, only to the precision known<input className={field} placeholder="YYYY, YYYY-MM, YYYY-MM-DD, or leave unknown" value={publicationDate} onChange={e=>setPublicationDate(e.target.value)}/></label>
      <label className="block text-sm">This file supersedes<select className={field} value={supersedesId} onChange={e=>setSupersedesId(e.target.value)}><option value="">No earlier version selected</option>{docs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
      <Button disabled={busy} type="submit">{busy?'Processing…':'Import & extract'}</Button>
    </form></TabsContent>
    <TabsContent value="sources"><div className="space-y-3 pt-3">{!docs.length&&<p>No sources yet. Import your first case file.</p>}{docs.map(d=><article className="rounded border p-3 space-y-2" key={d.id}><h4 className="font-semibold break-words">{d.name}</h4><p className="text-sm">{d.status} · Imported {d.importedAt} · Published {d.publicationDate??'unknown'}</p>{d.parentId&&<p className="text-sm">Email attachment · parent {d.parentId}</p>}{d.supersedesId&&<p className="text-sm">Amends document {d.supersedesId}; earlier original retained.</p>}{d.warnings.map((w,i)=><p className="text-sm" key={i}>{w}</p>)}<details className="text-sm"><summary>Original identity</summary><p className="break-all">SHA-256 {d.hash}</p><p className="break-all">Reference: {d.sourceUrl??'not supplied'}</p><p>Hash identifies bytes, not authenticity.</p></details><Button variant="outline" onClick={()=>download(`${endpoint}?action=original&id=${encodeURIComponent(d.id)}`,d.name)}>Download original</Button></article>)}</div></TabsContent>
    <TabsContent value="timeline"><div className="space-y-4 pt-3"><div className="flex flex-wrap items-center gap-3"><label className="text-sm">Show<select className={field} value={filter} onChange={e=>{setFilter(e.target.value);setLimit(10000)}}><option value="DRAFT">Needs review</option><option value="ACCEPTED">Reviewed</option><option value="REJECTED">Rejected</option><option value="ALL">All entries</option></select></label><p className="text-sm">Review confirms a faithful representation of the source—not that its allegation is true.</p></div>
    {filtered.length>1&&<div className="space-y-3 rounded bg-secondary p-4"><label className="text-sm">Timeline reveal: {Math.min(limit,filtered.length)} of {filtered.length} entries</label><Slider min={1} max={filtered.length} step={1} value={[Math.min(limit,filtered.length)]} onValueChange={v=>setLimit(v[0])} aria-label="Number of timeline entries to show"/><p className="text-sm">Ordered by stated event date; unknown dates appear last. No historical map state is inferred.</p></div>}
    {!filtered.length&&<p>No entries in this view. Imported text creates draft suggestions; image-only sources need manual transcription/OCR.</p>}{filtered.slice(0,limit).map(e=><ReviewEntry key={`${e.id}/${e.revision}`} entry={e} endpoint={endpoint} action={action} onSaved={()=>{setRevision(x=>x+1);onChanged?.()}}/>)}</div></TabsContent>
    <TabsContent value="search"><form className="space-y-3 pt-3" onSubmit={search}><label className="block text-sm">Find a phrase, permit number or name<input className={field} value={q} maxLength={160} onChange={e=>setQ(e.target.value)} required/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={earlier} onChange={e=>setEarlier(e.target.checked)}/>Include other cases I can access in this workspace</label><Button disabled={busy}>Search source passages</Button></form><div className="mt-4 space-y-3">{hits.map(h=><article key={h.id} className="rounded border p-3"><h4 className="font-semibold">{h.caseTitle} · {h.name}</h4><p className="text-sm">{h.locator}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{h.text}</p>{h.caseId!==caseId&&<Button className="mt-3" variant="outline" onClick={()=>onSelectCase(h.caseId)}>Open authorised case</Button>}</article>)}</div></TabsContent>
    <TabsContent value="export"><div className="space-y-4 pt-3"><p className="text-sm">Exports contain all accepted entries, including unknown dates and labelled superseded sources. Draft/rejected entries and originals are excluded. Current view filters do not change the export. This is not a redaction tool: review personal information before sharing.</p><Button variant="outline" disabled={busy} onClick={async()=>{try{await action({action:'exportPermission',enabled:true});setNotice('Export enabled for your case-owner account.')}catch(e){setError(textError(e))}}}>Case owner: enable my exports</Button><Button className="ml-3" disabled={busy} onClick={produce}>{busy?'Preparing…':'Create reviewed PDF'}</Button>{exportId&&<div className="flex flex-wrap gap-3"><Button variant="outline" onClick={()=>download(`${endpoint}?action=export&id=${encodeURIComponent(exportId)}`,'case-timeline.pdf')}>Download PDF</Button><Button variant="outline" onClick={()=>download(`${endpoint}?action=export&id=${encodeURIComponent(exportId)}&format=json`,'case-manifest.json')}>Download source manifest</Button></div>}</div></TabsContent>
    </Tabs></>}
  </section>
}
function ReviewEntry({entry:e,endpoint,action,onSaved}:{entry:Entry;endpoint:string;action:(x:Record<string,unknown>)=>Promise<unknown>;onSaved:()=>void}){
  const [history,setHistory]=useState<Revision[]|null>(null)
  const [title,setTitle]=useState(e.title),[quote,setQuote]=useState(e.quote),[date,setDate]=useState(e.eventDate??''),[precision,setPrecision]=useState(e.precision),[type,setType]=useState(e.evidenceType),[note,setNote]=useState(e.note),[error,setError]=useState(''),[passage,setPassage]=useState(''),[busy,setBusy]=useState(false)
  async function save(status:string){setBusy(true);setError('');try{await action({action:'review',eventId:e.id,revision:e.revision,title,quote,eventDate:precision==='UNKNOWN'?null:date,precision,evidenceType:type,note,status});onSaved()}catch(e){setError(textError(e))}finally{setBusy(false)}}
  return <article className="rounded-lg border p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">{e.eventDate??'Date unknown'} · {e.precision}</h4><span className="text-sm">{e.status} · revision {e.revision}</span></div>{e.superseded&&<p className="rounded bg-secondary p-2 text-sm">This source has an amendment. Review both versions; earlier evidence has not been deleted.</p>}<p className="text-sm text-muted-foreground">{e.name} · {e.locator}</p><p className="break-words">{e.title}</p><details><summary className="cursor-pointer text-sm font-medium">Inspect source & review entry</summary><div className="mt-3 space-y-3"><Button variant="outline" disabled={busy} onClick={async()=>{try{const r=await (await read(`${endpoint}?action=passage&id=${encodeURIComponent(e.passageId)}`)).json();setPassage(r.text)}catch(e){setError(textError(e))}}}>Read full source passage</Button>{passage&&<blockquote className="max-h-80 overflow-auto whitespace-pre-wrap break-words border-l-4 pl-3 text-sm">{passage}</blockquote>}
  <Button variant="outline" disabled={busy} onClick={async()=>{try{const r=await (await read(`${endpoint}?action=history&id=${encodeURIComponent(e.id)}`)).json();setHistory(r.revisions)}catch(err){setError(textError(err))}}}>Show review history</Button>
  {history&&<details open className="rounded border p-3"><summary>Earlier representations ({history.length})</summary><div className="mt-2 max-h-80 overflow-auto space-y-3">{history.map(r=><article className="border-b pb-2 text-sm" key={r.revision}><p>Revision {r.revision} · {r.status} · {r.createdAt}</p><p>{r.eventDate??'Date unknown'} · {r.precision} · {r.title}</p><blockquote className="whitespace-pre-wrap break-words">{r.quote}</blockquote><p>Reviewer: {r.reviewedBy??'Unreviewed extraction'}{r.note?` · ${r.note}`:''}</p></article>)}</div></details>}
  <label className="block text-sm">Event title<input className={field} value={title} maxLength={300} onChange={x=>setTitle(x.target.value)}/></label><label className="block text-sm">Exact supporting quote<textarea className={field} rows={4} value={quote} maxLength={2400} onChange={x=>setQuote(x.target.value)}/></label>
  <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Date precision<select className={field} value={precision} onChange={x=>setPrecision(x.target.value)}>{['UNKNOWN','YEAR','MONTH','DAY'].map(v=><option key={v}>{v}</option>)}</select></label><label className="block text-sm">Event date<input className={field} disabled={precision==='UNKNOWN'} placeholder="YYYY, YYYY-MM or YYYY-MM-DD" value={date} onChange={x=>setDate(x.target.value)}/></label></div><label className="block text-sm">Evidence type<select className={field} value={type} onChange={x=>setType(x.target.value)}>{['SOURCE_STATEMENT','REGULATOR_FINDING','MEASUREMENT','COMMUNITY_OBSERVATION','INFERENCE'].map(v=><option key={v}>{v}</option>)}</select></label><label className="block text-sm">Review rationale / unresolved question<textarea className={field} value={note} maxLength={2000} onChange={x=>setNote(x.target.value)}/></label><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>save('ACCEPTED')}>Accept source representation</Button><Button variant="outline" disabled={busy} onClick={()=>save('DRAFT')}>Keep draft</Button><Button variant="outline" disabled={busy} onClick={()=>save('REJECTED')}>Reject suggestion</Button></div></div></details>{error&&<p role="alert" className="text-sm">{error}</p>}</article>
}
