import type { BusinessCandidate, WildCounty, WildTopic } from './types'

const planned = (
  slug: string,
  name: string,
  province: WildCounty['province'],
  jurisdiction: WildCounty['jurisdiction'] = 'Ireland',
  aliases?: readonly string[],
): WildCounty => ({
  slug,
  name,
  brandName: `Wild ${name.replace(/^County /, '').replace(' / Londonderry', '')}`,
  province,
  jurisdiction,
  status: 'planned',
  aliases,
  topics: [],
  businessCandidates: [],
})

const downTopics: readonly WildTopic[] = [
  {
    slug: 'fens',
    title: 'Lecale Fens',
    summary: 'Four protected calcium-rich, spring-fed fen sites near Downpatrick, with reedbeds, pools and specialised wetland vegetation.',
    sourceUrl: 'https://www.daera-ni.gov.uk/protected-areas/lecale-fens',
    publisher: 'DAERA',
    evidenceScope: 'county',
    reviewStatus: 'source-reviewed',
    season: 'Late spring and summer bring the fen vegetation and dragonflies to life around the pools.',
    place: 'Lecale, near Downpatrick',
    lat: 54.33, lng: -5.72,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'oysters',
    title: 'Oysters and shellfish waters',
    summary: 'Official shellfish-water action material for named parts of Strangford Lough.',
    sourceUrl: 'https://www.daera-ni.gov.uk/sites/default/files/publications/daera/shellfish-action-plans-2019-proof-2.PDF',
    publisher: 'DAERA',
    evidenceScope: 'regional',
    reviewStatus: 'source-reviewed',
    caveat: 'The source concerns shellfish-water management; it is not a visitor safety notice or a claim about every oyster in the Lough.',
    season: 'Autumn and winter are the traditional season associated with native oysters.',
    place: 'Strangford Lough',
    lat: 54.37, lng: -5.55,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'owls',
    title: 'Barn owl context',
    summary: 'DAERA publishes a Northern Ireland species action plan for the barn owl.',
    sourceUrl: 'https://www.daera-ni.gov.uk/publications/northern-ireland-species-action-plan-barn-owl',
    publisher: 'DAERA',
    evidenceScope: 'national-context',
    reviewStatus: 'source-reviewed',
    caveat: 'This source does not establish a current barn owl record at a named County Down business or visitor site.',
    season: 'Barn owls hunt over rough grassland year-round, most visibly at dusk on still evenings.',
    place: 'Countywide context',
    lat: 54.33, lng: -5.72,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'strangford-lecale-aonb',
    title: 'Strangford & Lecale AONB',
    summary: 'A designated Area of Outstanding Natural Beauty covering the Lough, its drumlin islands, shoreline and Lecale coast.',
    sourceUrl: 'https://www.daera-ni.gov.uk/articles/strangford-and-lecale-aonb',
    publisher: 'DAERA',
    evidenceScope: 'regional',
    reviewStatus: 'source-reviewed',
    season: 'Autumn sees thousands of pale-bellied brent geese arrive on the Lough from the Arctic.',
    place: 'Strangford Lough & Lecale coast',
    lat: 54.38, lng: -5.55,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'murlough',
    title: 'Murlough National Nature Reserve',
    summary: 'A 6,000-year-old sand dune system managed as a National Nature Reserve, with heath, dunes and views to the Mournes.',
    sourceUrl: 'https://www.nationaltrust.org.uk/visit/northern-ireland/murlough-national-nature-reserve',
    publisher: 'National Trust',
    evidenceScope: 'county',
    reviewStatus: 'source-reviewed',
    season: 'Summer brings marram-covered dunes, wildflowers and butterflies; winter offers wide, quiet shore walks.',
    place: 'Dundrum Bay, near Newcastle',
    lat: 54.24, lng: -5.85,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'mourne-aonb',
    title: 'Mourne AONB',
    summary: 'The Mourne Mountains Area of Outstanding Natural Beauty, a landscape of granite peaks, upland heath and reservoirs.',
    sourceUrl: 'https://www.daera-ni.gov.uk/articles/mourne-aonb',
    publisher: 'DAERA',
    evidenceScope: 'regional',
    reviewStatus: 'source-reviewed',
    season: 'Late summer heather turns the lower slopes purple; clear autumn days give the longest views.',
    place: 'Mourne Mountains, near Newcastle',
    lat: 54.18, lng: -5.92,
    sourceChecked: '2026-09-14',
  },
]

const downCandidates: readonly BusinessCandidate[] = []

const kilkennyTopics: readonly WildTopic[] = [
  {
    slug: 'river-nore',
    title: 'River Nore',
    summary: 'Protected river habitats and qualifying species recorded for the wider River Barrow and River Nore SAC, which threads through the county.',
    sourceUrl: 'https://www.npws.ie/protected-sites/sac/002162',
    publisher: 'National Parks & Wildlife Service',
    evidenceScope: 'regional',
    reviewStatus: 'source-reviewed',
    caveat: 'A qualifying interest for the wider SAC is not automatically a record at a particular business or river access point.',
    season: 'Spring and early summer are the liveliest months along the river margins.',
    place: 'River Nore, Kilkenny city',
    lat: 52.654, lng: -7.252,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'otters',
    title: 'Otters',
    summary: 'Otter is an official qualifying interest of the River Barrow and River Nore SAC.',
    sourceUrl: 'https://www.npws.ie/protected-sites/sac/002162',
    publisher: 'National Parks & Wildlife Service',
    evidenceScope: 'regional',
    reviewStatus: 'source-reviewed',
    caveat: 'Precise or sensitive wildlife locations are not exposed, and this is not a sighting promise.',
    season: 'Otters are most often noticed at dawn and dusk in quieter stretches; they are present year-round.',
    place: 'Nore valley, near Inistioge',
    lat: 52.489, lng: -7.058,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'freshwater-pearl-mussel',
    title: 'Nore freshwater pearl mussel',
    summary: 'The Nore is associated with the critically endangered Nore freshwater pearl mussel, a qualifying interest of the SAC.',
    sourceUrl: 'https://www.npws.ie/protected-sites/sac/002162',
    publisher: 'National Parks & Wildlife Service',
    evidenceScope: 'regional',
    reviewStatus: 'source-reviewed',
    caveat: 'This is a protected, sensitive species. Locations are not exposed; the source concerns SAC designation, not a visitor activity.',
    season: 'A story of clean-water dependence best appreciated in low, clear summer flows from the bank.',
    place: 'Upper River Nore',
    lat: 52.79, lng: -7.34,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'castle-parklands',
    title: 'Kilkenny Castle Parklands',
    summary: 'The public parklands around Kilkenny Castle offer mature trees, riverside walks and open grassland in the heart of the city.',
    sourceUrl: 'https://heritageireland.ie/places-to-visit/kilkenny-castle/',
    publisher: 'Heritage Ireland (OPW)',
    evidenceScope: 'county',
    reviewStatus: 'source-reviewed',
    season: 'Autumn colour in the mature parkland trees is a highlight; spring brings blossom and birdsong.',
    place: 'Kilkenny Castle, Kilkenny city',
    lat: 52.6477, lng: -7.2487,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'dunmore-cave',
    title: 'Dunmore Cave & bats',
    summary: 'A limestone show cave north of the city, part of the karst landscape and a known roosting environment for bats.',
    sourceUrl: 'https://heritageireland.ie/places-to-visit/dunmore-cave/',
    publisher: 'Heritage Ireland (OPW)',
    evidenceScope: 'county',
    reviewStatus: 'source-reviewed',
    caveat: 'Bats are protected. The source concerns the visitor cave, not a licence to disturb roosting wildlife.',
    season: 'The cave is a cool, steady environment to explore year-round; bats are most active in the warmer months.',
    place: 'Dunmore Cave, near Ballyfoyle',
    lat: 52.732, lng: -7.246,
    sourceChecked: '2026-09-14',
  },
  {
    slug: 'woodstock',
    title: 'Woodstock Gardens & Arboretum',
    summary: 'Restored Victorian gardens and arboretum above the Nore at Inistioge, with notable tree collections and walks.',
    sourceUrl: 'https://woodstock.ie/',
    publisher: 'Woodstock Gardens & Arboretum',
    evidenceScope: 'county',
    reviewStatus: 'source-reviewed',
    season: 'Spring blossom and autumn leaf colour in the arboretum are the standout seasons.',
    place: 'Inistioge, Nore valley',
    lat: 52.487, lng: -7.055,
    sourceChecked: '2026-09-14',
  },
]

const kilkennyCandidates: readonly BusinessCandidate[] = []

export const WILD_COUNTIES: readonly WildCounty[] = [
  planned('antrim', 'Antrim', 'Ulster', 'Northern Ireland'),
  planned('armagh', 'Armagh', 'Ulster', 'Northern Ireland'),
  planned('carlow', 'Carlow', 'Leinster'),
  planned('cavan', 'Cavan', 'Ulster'),
  planned('clare', 'Clare', 'Munster'),
  planned('cork', 'Cork', 'Munster'),
  planned('derry-londonderry', 'Derry / Londonderry', 'Ulster', 'Northern Ireland', ['Derry', 'Londonderry']),
  planned('donegal', 'Donegal', 'Ulster'),
  {
    ...planned('down', 'County Down', 'Ulster', 'Northern Ireland'),
    brandName: 'Wild County Down',
    status: 'foundation',
    intro: 'County Down runs from the drumlins and tidal islands of Strangford Lough to the granite wall of the Mournes. Its protected fens, sand dunes and coastlines are documented by Northern Ireland’s own agencies and the National Trust — with every source kept in view.',
    topics: downTopics,
    businessCandidates: downCandidates,
  },
  planned('dublin', 'Dublin', 'Leinster'),
  planned('fermanagh', 'Fermanagh', 'Ulster', 'Northern Ireland'),
  planned('galway', 'Galway', 'Connacht'),
  planned('kerry', 'Kerry', 'Munster'),
  planned('kildare', 'Kildare', 'Leinster'),
  {
    ...planned('kilkenny', 'Kilkenny', 'Leinster'),
    status: 'foundation',
    intro: 'Kilkenny is Leinster’s medieval heart, shaped by the River Nore. Its story runs from the otters and freshwater pearl mussels of the Nore valley to the castle parklands, limestone caves and riverside gardens that ring the city — each with a source you can follow.',
    topics: kilkennyTopics,
    businessCandidates: kilkennyCandidates,
  },
  planned('laois', 'Laois', 'Leinster'),
  planned('leitrim', 'Leitrim', 'Connacht'),
  planned('limerick', 'Limerick', 'Munster'),
  planned('longford', 'Longford', 'Leinster'),
  planned('louth', 'Louth', 'Leinster'),
  planned('mayo', 'Mayo', 'Connacht'),
  planned('meath', 'Meath', 'Leinster'),
  planned('monaghan', 'Monaghan', 'Ulster'),
  planned('offaly', 'Offaly', 'Leinster'),
  planned('roscommon', 'Roscommon', 'Connacht'),
  planned('sligo', 'Sligo', 'Connacht'),
  planned('tipperary', 'Tipperary', 'Munster'),
  planned('tyrone', 'Tyrone', 'Ulster', 'Northern Ireland'),
  planned('waterford', 'Waterford', 'Munster'),
  planned('westmeath', 'Westmeath', 'Leinster'),
  planned('wexford', 'Wexford', 'Leinster'),
  planned('wicklow', 'Wicklow', 'Leinster'),
] as const

export function getWildCounty(slug: string): WildCounty | undefined {
  return WILD_COUNTIES.find((county) => county.slug === slug)
}

export function searchWildCounties(query: string): readonly WildCounty[] {
  const needle = query.trim().toLocaleLowerCase('en-IE')
  if (!needle) return WILD_COUNTIES

  return WILD_COUNTIES.filter((county) => {
    const searchable = [
      county.name,
      county.brandName,
      county.province,
      county.jurisdiction,
      ...(county.aliases ?? []),
      ...county.topics.flatMap((topic) => [topic.title, topic.summary]),
      ...county.businessCandidates.flatMap((business) => [business.name, business.locality, business.category]),
    ]
    return searchable.some((value) => value.toLocaleLowerCase('en-IE').includes(needle))
  })
}

