import Link from 'next/link'
import { PublicShell } from '@/components/wild/public-shell'
import { EvidenceLink } from '@/components/evidence-link'
import { enquiryHref } from '@/lib/enquiry/config'
export const metadata={title:'UK SRS evidence for listed companies | BioVeracity',description:'Connect a sustainability disclosure to the targets, metrics, source documents and later evidence behind it.'}
export default function UkSrsPage(){return <PublicShell>
<section className="bv-hero"><p className="bv-eyebrow">For UK listed-company sustainability, finance, legal and assurance teams</p><h1>Can you show the evidence<br/><em>behind what your company reports?</em></h1><p className="bv-intro">The FCA is asking in-scope listed companies to develop the data, metrics and targets needed to support UK SRS disclosures and establish internal controls and review processes. BioVeracity connects a disclosure to the evidence behind it and keeps that record as evidence changes.</p><div className="bv-actions"><Link className="bv-button" href={enquiryHref('srs-hero')}>Show us one disclosure →</Link><EvidenceLink className="bv-text-link" href="https://www.fca.org.uk/publications/newsletters/primary-market-bulletin-66">Read the FCA guidance</EvidenceLink></div><p>Send us one sustainability disclosure or target. See what its evidence record could look like.</p></section>
<section className="bv-section bv-tinted"><p className="bv-eyebrow">What you get</p><h2>Disclosure → target → evidence → chronology → review</h2><div className="bv-grid bv-three"><article className="bv-feature"><h3>What did we report?</h3><p>Keep the statement, target, metric and reporting period together.</p></article><article className="bv-feature"><h3>What supported it?</h3><p>Connect source documents, site evidence and external records with provenance.</p></article><article className="bv-feature"><h3>What happened afterwards?</h3><p>Read later evidence against the earlier statement and preserve uncertainty for human review.</p></article></div><div className="bv-actions"><Link className="bv-button" href={enquiryHref('srs-chain')}>Show us one disclosure →</Link></div><p className="bv-small">Send us one sustainability disclosure or target. See what its evidence record could look like.</p></section>
<section className="bv-section"><h2>Built for the review question.</h2><div className="bv-perspectives"><p>Evidence located</p><p>Evidence changed</p><p>Evidence not located</p><p>Human review required</p></div><p>BioVeracity organises evidence for review. It does not certify UK SRS compliance or turn an absent record into a legal conclusion.</p><div className="bv-actions"><Link className="bv-button" href={enquiryHref('srs-end')}>Show us one disclosure →</Link><Link className="bv-text-link" href="/evidence">See the evidence model →</Link></div></section>
</PublicShell>}
