// Immutable published wording: retain this version when issuing replacement terms.
export const termsSections = [
 ['Who provides the service', 'BioVeracity is a service of RippleXn. These terms cover account holders, professionals and venues. Any expressly agreed order or data-processing agreement also applies. Statutory rights and liabilities that cannot lawfully be excluded remain unaffected.'],
 ['Evidence and decision support', 'BioVeracity finds, organises, preserves and compares evidence. It does not certify ecological truth, regulatory compliance, causation or the absence of a species or event. Outputs do not replace qualified professional advice or the authority of a regulator. Customers must assess scope, review material source evidence and exercise their own professional judgement.'],
 ['Search coverage and absence', 'No record located or expected evidence not located means only that evidence was not located within the sources, area, parameters and period examined. It does not prove that an organism, event, survey or obligation did not exist. A gap or inconsistency does not itself establish breach, causation or ecological significance. Sources may be incomplete, unavailable, unindexed or affected by ingestion failures and methodology changes.'],
 ['Provenance, history and automated analysis', 'Source information remains subject to its original coverage, licensing and corrections. Where available, provenance identifies retrieval and publication dates and source versions. A snapshot records material retrieved by the service, not what a decision-maker actually knew or was required to know. Semantic ranking, summaries and duplicate groupings can be wrong. Copied records are not automatically independent confirmations. Check consequential findings against their sources.'],
 ['Your content and other people’s rights', 'You and the relevant rights holders retain existing rights in your uploads, photographs, captions and documents. Uploading does not transfer copyright to RippleXn or a venue. You must have authority to upload and permit the selected use. Facts are not automatically owned as copyright; third-party copyright, database rights, licences and personal-data rights continue to apply.'],
 ['Licence to operate the service', 'You grant RippleXn a non-exclusive licence to host, process, display and make authorised copies of your content only as needed to provide the service and carry out your publication instructions. Private case material is not licensed for public promotion. Future use of guest photographs in venue or BioVeracity publications requires the separate contributor release. We do not treat signup as permission to train general-purpose models or market to contributors.'],
 ['Venue cancellation and publication', 'Cancelling payment does not transfer ownership, delete your account or automatically withdraw a published venue page. Use Your data to take a page offline and request access, export or erasure. New publication still requires the existing approval process. We will not infer permission for new promotional use from a cancelled subscription. Separately authorised contributor licences and independently licensed public records are assessed on their own terms.'],
 ['Leaving, retention and copies', 'Data-rights requests remain available without a paid subscription. We review erasure against other people’s rights, the customer’s controller instructions and any applicable legal obligations or legal claims. We explain any data retained, the reason and the retention period or criteria. A habitat’s 30-year management obligation is not a blanket licence to retain personal data for 30 years. Downloaded, printed or previously distributed copies may not be recoverable; where required we take reasonable steps concerning recipients and future use.'],
 ['Service responsibility', 'We will exercise the skill and care required by applicable law. The limitations above describe the scope of the service; they do not excuse our own failure to meet our obligations. An output is not a certification or confirmation of compliance unless that specific service has been expressly agreed in writing.'],
] as const
export const privacySections = [
 ['Who is responsible', 'RippleXn operates BioVeracity and determines the purposes of account administration, service security and managing publication permissions. For private professional case material we may act as processor for the customer controller under a separate data-processing agreement. Contact us through the Contact page about any privacy request, including if you have no account.'],
 ['Information and purposes', 'We process account and contact details, password hashes, terms-acceptance records, billing references, preferences, activity records, enquiries, uploads, venue content and contributor releases. These support the service, security, requests and authorised publication. Contributor contact names and emails are private and are not included in public photo feeds or ordinary venue downloads. A public photographer credit can be a pseudonym.'],
 ['Lawful bases and choices', 'Account services and requested processing rely on contract where applicable; security and rights administration may rely on legitimate interests, and applicable legal duties on legal obligation. Optional publication permissions and optional communications are separate choices. Acknowledging this notice is not blanket GDPR consent. Where processing relies on consent, you can withdraw it without affecting the lawfulness of earlier processing.'],
 ['Who receives data', 'Authorised venue users and professional collaborators receive only content within their permissions. Hosting, storage, authentication, payment, email and scanning providers process data as needed to deliver the service. Guest photo uploads explicitly identify Cloudmersive scanning before submission. Publication makes approved content and its selected credit public, not the private contributor contact record. We do not sell personal information or use it for advertising profiles. Contact us for the applicable processors, locations and transfer safeguards for your service.'],
 ['Retention and leaving', 'We keep personal data only for the purpose and period justified by the service, applicable legal duties and the defence of legal claims. Cancellation and erasure are distinct. A request response explains any exceptions, recipient handling and backup deletion arrangements. Shared case evidence and third-party public records require separate assessment. No indefinite personal-data retention follows merely from a 30-year ecological obligation.'],
 ['Access, portability and other rights', 'Your data provides a limited instant account download plus requests for full access, erasure, correction, restriction, objection and portability where applicable. Access and portability are different rights. We normally respond without undue delay and within one calendar month; if an extension is legally available we explain it within the initial period. We may need proportionate identity verification and must protect other people’s data. Requests do not require payment, and Contact remains an alternative route.'],
 ['Complaints', 'You can complain to the Irish Data Protection Commission or the UK Information Commissioner, as applicable, or your competent supervisory authority. You can contact us first, but that is not a condition of making a complaint.'],
] as const
