// Shared configuration for the self-contained parser worker bundle.
//
// Both scripts/build-parser-worker.mjs (which writes the committed artifacts)
// and scripts/check-parser-worker.mjs (which verifies they are still in sync
// with the source and dependencies) import this module, so the exact esbuild
// options can never drift between building and checking.
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
export const root = path.resolve(here, '..')

export const entry = path.join(root, 'lib', 'workspaces', 'parser-process.mjs')
export const outfile = path.join(root, 'public', 'parser', 'worker.mjs')
export const licensesFile = path.join(root, 'public', 'parser', 'worker.LICENSES.txt')
export const manifestFile = path.join(root, 'public', 'parser', 'worker.manifest.json')

// The source files that esbuild reads directly (the worker entry graph, plus
// the launcher that resolves and forks the bundle). Any change to these should
// invalidate the committed bundle, so they are hashed into the manifest.
export const sourceFiles = [
  path.join(root, 'lib', 'workspaces', 'parser-process.mjs'),
  path.join(root, 'lib', 'workspaces', 'parse-file.mjs'),
  path.join(root, 'lib', 'workspaces', 'parser.ts'),
]

// Heavy third-party dependencies inlined into the bundle at build time.
export const bundledDeps = ['pdfjs-dist', 'mammoth', 'mailparser']

// The esbuild options shared by build and check. Callers pass outfile/write.
export function buildOptions(overrides = {}) {
  return {
    entryPoints: [entry],
    bundle: true,
    platform: 'node',
    // ESM output (not CJS): pdfjs-dist's legacy build calls
    // createRequire(import.meta.url) internally. In a CJS bundle esbuild sets
    // import.meta to {}, so import.meta.url is undefined and pdfjs throws while
    // extracting text. ESM output preserves a real import.meta.url.
    format: 'esm',
    target: 'node20',
    // Inline everything. The worker must have zero runtime module dependencies.
    external: [],
    legalComments: 'none',
    logLevel: 'silent',
    // Some inlined CommonJS dependencies (e.g. mammoth) call require('fs') and
    // other Node built-ins. In ESM output esbuild routes unresolved requires
    // through a __require shim that throws unless a real top-level `require`
    // exists. Defining one via createRequire(import.meta.url) lets those
    // built-in requires resolve at runtime; every third-party module is already
    // statically inlined, so nothing is fetched from node_modules on the host.
    banner: {
      js: [
        '/* AUTO-GENERATED by scripts/build-parser-worker.mjs. Do not edit by hand. */',
        "import { createRequire as __bvCreateRequire } from 'node:module';",
        'const require = __bvCreateRequire(import.meta.url);',
      ].join('\n'),
    },
    ...overrides,
  }
}
