import Link from 'next/link'
import { PublicShell } from '@/components/wild/public-shell'
import { WildEnquiry } from '@/components/wild/wild-enquiry'

export const metadata = { title: 'Your place. The wild on your doorstep. | BioVeracity', description: 'Your own visitor page, personalised signage and a dedicated QR code. Upfront signage and monthly BioVeracity Wild community membership. Contact us for pricing.' }
const benefits = [
  ['01', 'Your story, beautifully presented.', 'Your photographs, products, experiences and visitor information, together on your own page.'],
  ['02', 'A wider world on your doorstep.', 'Connect your place with sourced stories about the nature, landscape and heritage of your area.'],
  ['03', 'One scan starts the discovery.', 'Your own QR code opens your venue page. Use it on your sign, menus, packaging and reception desk.'],
  ['04', 'Part of your Wild County.', 'Join a community of places that help visitors discover their surroundings. Your own website stays at the heart of your business.'],
]
export default function PartnersPage() {
  return <PublicShell>
    <section className="bv-hero bv-split"><div><p className="bv-eyebrow">The BioVeracity Wild community</p><h1>Your ecology hub.<br /><em>A fresh story<br />for every season.</em></h1><p className="bv-intro">Your photographs, local nature stories and a seasonal guest guide. Built for hotels, guesthouses, food, craft and visitor experiences.</p><div className="bv-actions"><Link className="bv-button" href="/wild/studio">Create your ecology hub</Link><a className="bv-text-link" href="#enquire">Contact us for pricing</a><Link className="bv-text-link" href="/wild/places/example-woodland-venue">See an example ↗</Link></div><p className="bv-small">Personalised signage upfront. Community membership monthly.</p></div><figure className="bv-sign"><img src="/wild/venue-signage-sample.png" width="1254" height="1254" alt="Sample personalised Wild County Down plaque with oak leaves and green and gold lettering" fetchPriority="high" /><figcaption>Sample signage · Personalised with your venue name.</figcaption></figure></section>
    <section className="bv-section"><p className="bv-eyebrow">What membership brings</p><h2>A place worth visiting.<br />A story worth exploring.</h2><div className="bv-grid bv-four">{benefits.map(([n,title,body])=><article className="bv-feature" key={n}><span className="bv-number">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="bv-section bv-tinted bv-split"><div><p className="bv-eyebrow">See how it comes together</p><h2>Your content.<br /><em>Your wider world.</em></h2><p>Start with the people, products and experiences that make your venue yours. Then invite guests into the stories of the surrounding area.</p><p>Your website, shop or booking link stays easy to find. Guests explore without downloading an app or creating an account.</p><Link className="bv-button bv-green" href="/wild/places/example-woodland-venue">Explore the example venue ↗</Link><p className="bv-small">Fictional example. Your page would use your approved content.</p></div><div className="bv-phone"><div className="bv-phone-top">WILD COUNTY DOWN <span>Example</span></div><div className="bv-phone-story"><p className="bv-eyebrow">Start here</p><h3>Your venue<br />in the wild</h3><p>Your food. Your people. Your story.</p><span className="bv-pill">Your website ↗</span></div><div className="bv-phone-bottom"><p className="bv-eyebrow">Discover the wider area</p><h4>Strangford Lough</h4><p>Explore the sources behind its shellfish waters.</p><hr /><h4>Lecale Fens</h4><p>Discover a different side of County Down.</p><Link href="/wild/places/example-woodland-venue">Open the full example →</Link></div></div></section>
    <section className="bv-section"><p className="bv-eyebrow">Simple from the start</p><h2>Build it. Review it. Make it yours.</h2><div className="bv-grid bv-three">{[['1','Create your private hub.','Sign in, choose your county and add your story, website and photographs.'],['2','Generate and review your seasons.','Create twelve monthly drafts, add optional Google Trends data and edit your guest prompts and marketing captions.'],['3','Publish your approved version.','Your hub and QR become available after approval. The monthly feature changes within your approved plan year. Signage and membership terms are agreed separately.']].map(([n,t,b])=><article className="bv-feature" key={n}><span className="bv-number">{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
    <section className="bv-section bv-pricing"><p className="bv-eyebrow">A clear arrangement</p><h2>A one-off cost to get started.<br /><em>Monthly membership to stay connected.</em></h2><div className="bv-grid bv-two"><article><h3>Your signage</h3><p>Pay upfront for personalised signage, with your own venue QR code.</p></article><article><h3>Your membership</h3><p>Pay monthly for your place in the BioVeracity Wild community. Your quote explains the content and support included.</p></article></div><p>We agree the full cost, delivery and membership terms before you commit.</p><a className="bv-button" href="#enquire">Contact us for pricing</a></section>
    <section className="bv-section bv-split" id="enquire"><div><p className="bv-eyebrow">Start a conversation</p><h2>Tell us about<br /><em>your place.</em></h2><p>We’ll contact you to discuss your venue, prepare a proposal and explain pricing.</p><p className="bv-small">No account or payment details needed. Submitting this form does not start a subscription.</p></div><WildEnquiry /></section>
    <section className="bv-section bv-faq"><p className="bv-eyebrow">A few useful answers</p><h2>Before you join.</h2>{[['Do I need a new website?','No. Your BioVeracity page links to your existing website, shop or booking service.'],['Can I use my own photographs and stories?','Yes. You approve the material used and confirm that you have permission to share it.'],['What does my QR code open?','Your venue page, combining your approved content with discoveries from the wider area. Its address stays stable when the page is updated.'],['What is included each month?','Your proposal sets out the page, local content, updates and support included in your membership, together with the monthly price and cancellation terms.'],['Is this an environmental certification?','No. The sign identifies participation in the BioVeracity Wild community. Environmental stories remain connected to their sources.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  </PublicShell>
}
