import { EvidenceLink } from '@/components/evidence-link'
import Link from 'next/link'
import { PublicShell } from '@/components/wild/public-shell'
import { WildEnquiry } from '@/components/wild/wild-enquiry'

export const metadata = { title: 'Put your place at the centre of its local ecology | BioVeracity', description: 'Your own visitor page, personalised signage and a dedicated QR code. Upfront signage and monthly BioVeracity Wild community membership. Contact us for pricing.' }
const benefits = [
  ['01', 'Your story, beautifully presented.', 'Your photographs, products, experiences and visitor information, together on your own page.'],
  ['02', 'A meeting point for local ecology.', 'Connect your place with sourced stories, local discoveries and the people paying attention to the landscape around it.'],
  ['03', 'One scan starts the discovery.', 'Your own QR code opens your venue page. Use it on your sign, menus, packaging and reception desk.'],
  ['04', 'Part of your Wild County.', 'Become one of the physical places where people can discover, notice and return to the ecology of the county. Your own website stays at the heart of your business.'],
]
export default function PartnersPage() {
  return <PublicShell>
    <section className="bv-hero bv-split"><div><p className="bv-eyebrow">For venues & places rooted in their landscape</p><h1>Put your place at the centre<br /><em>of its local ecology.</em></h1><p className="bv-intro">Connect your venue with the wildlife, landscape, local knowledge and source-linked environmental stories around it. Give visitors a reason to notice what changes from one season to the next.</p><div className="bv-actions"><Link className="bv-button" href="#enquire">Enquire about a founding partnership</Link><EvidenceLink className="bv-text-link" href="#enquire">Contact us for pricing</EvidenceLink><Link className="bv-text-link" href="/wild/places/example-woodland-venue">See an example ↗</Link></div><p className="bv-small">Personalised signage upfront. Community membership monthly.</p></div><figure className="bv-venue-network"><div className="bv-network-plaque"><img src="/wild/venue-signage-sample.png" width="1254" height="1254" alt="Example personalised Wild County plaque with oak leaves and green and gold lettering, shown for County Down" fetchPriority="high" /><span className="bv-network-tag">Example · Wild County Down</span></div><figcaption><p className="bv-eyebrow">A growing network</p><p>Participating places across Ireland's Wild Counties — each with its own personalised plaque and QR code.</p><ul className="bv-network-chips"><li>Kilkenny</li><li>Down</li><li>+ more counties opening</li></ul></figcaption></figure></section>
    <section className="bv-section"><p className="bv-eyebrow">What membership brings</p><h2>A place worth visiting.<br />A story worth exploring.</h2><div className="bv-grid bv-four">{benefits.map(([n,title,body])=><article className="bv-feature" key={n}><span className="bv-number">{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="bv-section bv-tinted bv-split"><div><p className="bv-eyebrow">See how it comes together</p><h2>Your content.<br /><em>Your wider world.</em></h2><p>Start with the people, products and experiences that make your venue yours. Then invite guests into the stories of the surrounding area.</p><p>Your website, shop or booking link stays easy to find. Guests explore without downloading an app or creating an account.</p><Link className="bv-button bv-green" href="/wild/places/example-woodland-venue">Explore the example venue ↗</Link><p className="bv-small">Fictional example. Your page would use your approved content.</p></div><div className="bv-phone"><div className="bv-phone-top">WILD COUNTY DOWN <span>Example</span></div><div className="bv-phone-story"><p className="bv-eyebrow">Start here</p><h3>Your venue<br />in the wild</h3><p>Your food. Your people. Your story.</p><span className="bv-pill">Your website ↗</span></div><div className="bv-phone-bottom"><p className="bv-eyebrow">Discover the wider area</p><h4>Strangford Lough</h4><p>Explore the sources behind its shellfish waters.</p><hr /><h4>Lecale Fens</h4><p>Discover a different side of County Down.</p><Link href="/wild/places/example-woodland-venue">Open the full example →</Link></div></div></section>
    <section className="bv-section"><p className="bv-eyebrow">Simple from the start</p><h2>Tell us. We prepare it with you. You approve.</h2><div className="bv-grid bv-three">{[['1','Tell us about your place.','Send a short enquiry with your venue and website. We reply to arrange a conversation — no account needed.'],['2','We prepare your seasons with you.','Our team drafts your page, twelve monthly features, guest prompts and marketing captions from the photographs and words you approve.'],['3','You approve. We publish.','Once you sign off, your hub and QR go live. The monthly feature changes within your plan year. Signage and membership terms are set out in your proposal.']].map(([n,t,b])=><article className="bv-feature" key={n}><span className="bv-number">{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></section>
    <section className="bv-section bv-pricing"><p className="bv-eyebrow">A clear arrangement</p><h2>A one-off cost to get started.<br /><em>Monthly membership to stay connected.</em></h2><div className="bv-grid bv-two"><article><h3>Your signage</h3><p>Pay upfront for personalised signage, with your own venue QR code.</p></article><article><h3>Your membership</h3><p>Pay monthly for your place in the BioVeracity Wild community. Your quote explains the content and support included.</p></article></div><p>We agree the full cost, delivery and membership terms before you commit.</p><EvidenceLink className="bv-button" href="#enquire">Contact us for pricing</EvidenceLink></section>
    <section className="bv-section bv-split" id="enquire"><div><p className="bv-eyebrow">Start a conversation</p><h2>Tell us about<br /><em>your place.</em></h2><p>We’ll contact you to discuss your venue, prepare a proposal and explain pricing.</p><p className="bv-small">No account or payment details needed. Submitting this form does not start a subscription.</p></div><WildEnquiry /></section>
    <section className="bv-section bv-faq"><p className="bv-eyebrow">A few useful answers</p><h2>Before you join.</h2>{[['Do I need a new website?','No. Your BioVeracity page links to your existing website, shop or booking service.'],['Can I use my own photographs and stories?','Yes. You approve the material used and confirm that you have permission to share it.'],['What does my QR code open?','Your venue page, combining your approved content with discoveries from the wider area. Its address stays stable when the page is updated.'],['What is included each month?','Your proposal sets out the page, local content, updates and support included in your membership, together with the monthly price and cancellation terms.'],['Is this an environmental certification?','No. The sign identifies participation in the BioVeracity Wild community. Environmental stories remain connected to their sources.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  </PublicShell>
}
