'use client'
import { EvidenceLink } from '@/components/evidence-link'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { TERMS_VERSION, PRIVACY_VERSION, TERMS_LABEL } from '@/lib/data-rights/policy'
type Rights = {galleryReleases:{photoId:string;venueName:string;withdrawnAt:string|null}[];acceptances:{termsVersion:string;privacyVersion:string}[]; requests:{id:string;kind:string;status:string;dueAt:string;response:string}[]; venues:{id:string;profile:{name?:string};isPublished:boolean}[]}
export function DataRights() {
 const [data,setData]=useState<Rights|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [kind,setKind]=useState('ACCESS'),[details,setDetails]=useState(''),[confirm,setConfirm]=useState(''),[accept,setAccept]=useState(false)
 async function load(){const r=await fetch('/api/account/data',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 async function post(input:Record<string,unknown>,success:string){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/account/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const j=await r.json();if(!r.ok)throw Error(j.error);await load();setMessage(success);setConfirm('')}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 const current=data?.acceptances.some(a=>a.termsVersion===TERMS_VERSION&&a.privacyVersion===PRIVACY_VERSION)
 return <section className="rounded-xl border p-6 space-y-5"><h2 className="text-2xl font-bold">Your data</h2><p>You remain in control when a subscription ends. Cancelling payment, taking a page offline and requesting deletion are separate actions.</p>
 {error&&<p role="alert">{error} <Link className="underline" href="/contact">Contact us</Link></p>}{message&&<p role="status">{message}</p>}
 {!data&&!error&&<p role="status">Loading your data controls…</p>}
 {data&&<><p><EvidenceLink className="underline" href="/api/account/data/download">Download account data (JSON)</EvidenceLink></p><p className="text-sm">Includes account details, preferences, terms records, requests and owned venue profiles/plans and gallery releases. For photographs use the venue studio downloads. For case material, logs and all other personal data, request full access below.</p>
 {!current&&<div className="space-y-3"><p><Link className="underline" href="/terms" target="_blank">Read Terms and Conditions</Link> · <Link className="underline" href="/privacy" target="_blank">Privacy Notice</Link></p><label className="flex gap-3"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>{TERMS_LABEL}</label><button className="rounded border px-4 py-2" disabled={busy||!accept} onClick={()=>post({action:'accept',acceptTerms:accept,termsVersion:TERMS_VERSION,privacyVersion:PRIVACY_VERSION},'Terms acceptance saved.')}>Record my acceptance</button><p className="text-sm">Your data rights remain available whether or not you accept updated terms.</p></div>}
 {data.venues.map(v=><div className="rounded border p-4" key={v.id}><h3 className="font-semibold">{v.profile.name||'Your venue'}</h3><p>{v.isPublished?'Public page is on':'Public page is off'}</p>{v.isPublished&&<button className="underline" disabled={busy} onClick={()=>post({action:'unpublish',hubId:v.id},'Venue page taken offline. Stored content has not been deleted.')}>Turn public page off</button>}<p className="text-sm">Publishing again requires the venue studio’s approval process.</p></div>)}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();post({kind,details,confirm},'Request received. No data has been deleted by submitting this form. Track the response below.')}}><h3 className="text-xl font-semibold">Exercise your data rights</h3><label className="block">Request<select className="block w-full border p-2" value={kind} onChange={e=>{setKind(e.target.value);setConfirm('')}}><option value="ACCESS">Access my personal data (full request)</option><option value="PORTABILITY">Request a portable copy</option><option value="ERASURE">Request deletion of my data</option><option value="RECTIFICATION">Correct my data</option><option value="RESTRICTION">Restrict processing</option><option value="OBJECTION">Object to processing</option></select></label><label className="block">Details (optional)<textarea className="block w-full border p-2" value={details} onChange={e=>setDetails(e.target.value)} maxLength={4000}/></label>
 {kind==='ERASURE'&&<div><p>Download anything you need first. We will review shared records, other people’s rights and legal retention duties, explain any exceptions and confirm the outcome. This does not cancel billing; manage your subscription separately.</p><label>Type DELETE MY DATA<input className="block w-full border p-2" value={confirm} onChange={e=>setConfirm(e.target.value)} required pattern="DELETE MY DATA" autoComplete="off"/></label></div>}
 <button className="rounded border px-4 py-2" disabled={busy||kind==='ERASURE'&&confirm!=='DELETE MY DATA'}>{busy?'Saving…':'Submit request'}</button><p className="text-sm">No paid plan needed. We normally respond within one calendar month. You can also <Link className="underline" href="/contact">contact us</Link>.</p></form>
 <h3 className="font-semibold">Gallery publication permissions</h3><p>Your release records are included in the account download.</p>{data.galleryReleases.map(r=><div key={r.photoId}><p>{r.venueName} · {r.photoId}</p>{r.withdrawnAt?<p>Future-publication permission withdrawn</p>:<button className="underline" disabled={busy} onClick={()=>post({action:'withdrawGalleryRelease',photoId:r.photoId},'Future-publication permission withdrawn. Your gallery photo remains until you remove it in the studio.')}>Withdraw future-publication permission</button>}</div>)}
 <h3 className="font-semibold">Your requests</h3>{!data.requests.length&&<p>No requests yet.</p>}{data.requests.map(q=><article className="border-t pt-3" key={q.id}><p>{q.kind} · {q.status.replace(/_/g,' ')}</p><p className="text-sm">Reference {q.id} · Response due {new Date(q.dueAt).toLocaleDateString('en-GB')}</p>{q.response&&<p className="whitespace-pre-wrap">{q.response}</p>}</article>)}</>}
 </section>
}
