 'use client'
import {useEffect,useState} from 'react'
type Item={id:string;email:string;kind:string;details:string;status:string;dueAt:string;response:string}
type Release={photoId:string;contactName:string;contactEmail:string;venueName:string;caption:string;venuePublications:boolean;bioPublications:boolean;contactVerifiedAt:string|null}
export function RightsAdmin(){
 const [items,setItems]=useState<Item[]>([]),[releases,setReleases]=useState<Release[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function get(path:string){const r=await fetch(path,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);return j}
 async function load(){setItems(await get('/api/admin/data-rights'));try{setReleases(await get('/api/admin/photo-releases'))}catch(e){setMessage(e instanceof Error?e.message:'Release queue unavailable')}}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
 async function clearance(photoId:string,use:string){setBusy(true);try{const r=await fetch('/api/admin/photo-releases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({photoId,use})});const j=await r.json();if(!r.ok)throw Error(j.error);const url=URL.createObjectURL(new Blob([JSON.stringify({...j,use,checkedAt:new Date().toISOString()},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='publication-permission.json';a.click();URL.revokeObjectURL(url);setMessage('Permission checked now. Recheck before each new use; this record does not override a later withdrawal.')}catch(e){setMessage(e instanceof Error?e.message:'Check failed')}finally{setBusy(false)}}
 async function post(path:string,input:Record<string,unknown>){setBusy(true);setMessage('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const j=await r.json();if(!r.ok)throw Error(j.error);await load();setMessage('Saved. No email or deletion was performed by this update.')}catch(e){setMessage(e instanceof Error?e.message:'Update failed')}finally{setBusy(false)}}
 return <div className="space-y-6"><h1 className="text-3xl font-bold">Data rights and contributor releases</h1><p>This queue is operational: review it daily. Confirm identity proportionately, collect or erase data through the approved runbook, then record the outcome. Updating a status does not perform deletion, export or notification. Deliver responses securely and tell the requester how to complain.</p>{message&&<p role="status">{message}</p>}<h2 className="text-xl font-bold">Rights requests</h2>{items.length===0&&<p>No requests loaded.</p>}{items.map(q=><form key={q.id} className="border rounded p-4 space-y-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);post('/api/admin/data-rights',{id:q.id,status:d.get('status'),response:d.get('response'),confirm:d.get('confirm')==='on'})}}><h3>{q.kind} · {q.email}</h3><p>{q.id} · {q.status} · Due {new Date(q.dueAt).toLocaleDateString('en-GB')}</p><p className="whitespace-pre-wrap">{q.details}</p>{['RECEIVED','IN_REVIEW'].includes(q.status)?<><label>Status<select name="status" className="block border p-2"><option>IN_REVIEW</option><option>COMPLETED</option><option>PARTIALLY_COMPLETED</option><option>REFUSED</option></select></label><label>Response visible to requester<textarea className="block border w-full p-2" name="response" required minLength={20} maxLength={4000} defaultValue={q.response}/></label><label className="block"><input type="checkbox" name="confirm"/> I have completed the stated work and recorded retention grounds, periods and complaint rights where relevant.</label><button className="border p-2" disabled={busy}>Record response</button></>:<p>{q.response}</p>}</form>)}
 <h2 className="text-xl font-bold">Private contributor releases</h2><p>Contact details are self-declared. Independently verify contact and rights before marking verified. Do not send marketing. Publication also needs the relevant optional permission and editorial approval; recheck immediately before every new use.</p>{releases.map(r=><form key={r.photoId} className="border rounded p-4 space-y-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);post('/api/admin/photo-releases',{action:'verify',photoId:r.photoId,note:d.get('note')})}}><h3>{r.venueName} · {r.caption}</h3><p>{r.contactName} · {r.contactEmail}</p><p>Venue publications: {r.venuePublications?'Permitted':'Not permitted'} · BioVeracity publications: {r.bioPublications?'Permitted':'Not permitted'}</p><p>{r.contactVerifiedAt?'Contact and authority recorded as verified':'Verification required before future publication'}</p><label>Evidence of independent contact and authority verification<textarea name="note" className="border block w-full" minLength={20} maxLength={2000} required/></label><button className="border p-2" disabled={busy}>Record verification</button><button type="button" className="border p-2" disabled={busy||!r.venuePublications||!r.contactVerifiedAt} onClick={()=>clearance(r.photoId,'venue')}>Check venue publication permission</button><button type="button" className="border p-2" disabled={busy||!r.bioPublications||!r.contactVerifiedAt} onClick={()=>clearance(r.photoId,'bioveracity')}>Check BioVeracity publication permission</button></form>)}</div>
}
