import Link from 'next/link'
import { PublicShell } from '@/components/wild/public-shell'
export const metadata={title:'Understand a site | BioVeracity',description:'Bring environmental records together to review what is known about a site, follow sources and identify questions that need further evidence.'}
export default function ProfessionalsPage(){return <PublicShell>
<section className="bv-hero"><p className="bv-eyebrow">For ecology & environmental decisions</p><h1>Understand a site.<br /><em>Follow the evidence.</em></h1><p className="bv-intro">Bring scattered environmental records and your own documents into a clearer picture of a place. Examine what is known, where accounts differ and what needs checking.</p><div className="bv-actions"><Link className="bv-button" href="/search">Explore the evidence</Link><Link className="bv-text-link" href="/contact">Discuss your use case ↗</Link></div></section>
<section className="bv-section"><p className="bv-eyebrow">One place. A clearer view.</p><h2>For the questions<br />that need an answer.</h2><div className="bv-grid bv-three">{[['Ecology & environmental advice','Consider public environmental records alongside your own professional findings. Keep record dates, geographical scope and uncertainty visible.'],['Evidence review','Bring source material together around a place, follow changes over time and identify what still needs to be established.'],['Reports & casework','Keep the source, date and evidence trail attached as material moves into private casework and review.']].map(([t,b])=><article className="bv-feature" key={t}><h3>{t}</h3><p>{b}</p></article>)}</div></section>
<section className="bv-section" id="bng"><p className="bv-eyebrow">Biodiversity Net Gain</p><h2>The metric is a moment.<br /><em>The evidence lasts for decades.</em></h2><p>A Biodiversity Net Gain commitment can outlive project teams, consultants and systems. BioVeracity keeps the baseline, surveys, commitments, monitoring evidence and later changes connected to the place they concern — with the original sources attached.</p><p><strong>Baseline → Surveys → Commitment → Monitoring → Evidence → Next obligation</strong></p>
<h3>Your BNG Evidence Record includes</h3><div className="bv-grid bv-three">{[['The original evidence','Baseline surveys, reports and commitments kept as their original documents, with dates and sources attached.'],['What was promised','Each commitment recorded in the words of its source, with who is responsible and by when, where stated.'],['What happens next','Monitoring deadlines and recurring obligations kept visible, so the next required action is not lost.'],['A record someone else can inherit','A source-linked record a future team can pick up, without losing why each entry is there.']].map(([t,b])=><article className="bv-feature" key={t}><h3>{t}</h3><p>{b}</p></article>)}</div>
<h3>What are you buying?</h3><p>One private evidence record for a real BNG project or site. This is not a national dataset and makes no claim to cover every place — it is a working record for the project you bring.</p>
<h3>How it is set up</h3><p>You give us the project. BioVeracity builds the initial BNG Evidence Record from agreed public evidence and the documents you provide. Your team reviews it and maintains the source-linked record as the project progresses.</p><p>It is built for developers and infrastructure promoters; ecology and environment teams; planning and consenting teams; environmental consultancies; local authorities; and habitat and land managers who need one commitment to stay legible for years.</p>
<h3>What this does not do</h3><p>This does not calculate the statutory biodiversity metric, certify BNG compliance, or make statutory planning decisions. It does not replace an ecologist, Natural England or the local planning authority. It never treats “evidence not located” as proof that an obligation was missed — only that a documented search of a stated scope did not locate the evidence.</p>
<div className="bv-actions"><Link className="bv-button bv-green" href="/workspace/bng">Start a BNG Evidence Record</Link><Link className="bv-text-link" href="/contact">Discuss a managed setup →</Link></div>
<article className="bv-feature"><h3>Demonstration: following a major infrastructure project’s biodiversity evidence</h3><p>A worked example follows the biodiversity evidence around the Grimsby to Walpole electricity transmission project in eastern England, promoted by National Grid. It is illustrative only; National Grid is named as the scheme’s promoter, not as a customer or partner. Public English evidence is brought in by agreement during a managed setup rather than pulled automatically.</p><p><strong>Worked demonstration — coming soon.</strong></p></article></section>
<section className="bv-section bv-tinted" id="sustainability"><p className="bv-eyebrow">For sustainability & environmental managers</p><h2>Years of reports.<br /><em>One evidence chronology.</em></h2><p>Bring environmental reports, engineering studies, monitoring results and commitments together around the place they concern. Follow what was reported, what changed, what was measured and where the source evidence still leaves a question open.</p><div className="bv-grid bv-three"><article className="bv-feature"><h3>Follow the chronology</h3><p>Keep event dates, publication dates and later evidence distinct instead of flattening years of work into one summary.</p></article><article className="bv-feature"><h3>Keep engineering evidence in context</h3><p>Review reports and monitoring alongside environmental records without losing the original source or document trail.</p></article><article className="bv-feature"><h3>Record what is unresolved</h3><p>Preserve gaps and conflicting accounts rather than turning uncertainty into a conclusion.</p></article></div><div className="bv-actions"><Link className="bv-button bv-green" href="/login?callbackUrl=%2Fworkspace">Build your evidence record</Link><Link className="bv-text-link" href="/contact">Discuss your use case →</Link></div></section>
<section className="bv-section bv-split"><div><p className="bv-eyebrow">The professional experience</p><h2>Sources you can follow.<br /><em>Questions you can examine.</em></h2><p>BioVeracity helps you bring environmental information together. The original record, its date and its relationship to the place remain essential to interpretation.</p><Link className="bv-button bv-green" href="/login?callbackUrl=%2Fworkspace">Sign in to your account</Link></div><article className="bv-feature"><h3>A shared foundation. Distinct purposes.</h3><p>Wild Counties presents public nature and local stories. Professional work focuses on evidence review.</p><p>A venue’s paid membership does not validate its environmental performance or grant access to private case material.</p><Link href="/contact">Contact us for pricing →</Link></article></section>
</PublicShell>}
