import { HubError, record } from '../wild-hubs/domain'
export const RELEASE_VERSION = 'venue-photo-release-2026-09-22.1'
export const RELEASE_CORE = 'I keep copyright and grant RippleXn (BioVeracity) and this venue a non-exclusive, royalty-free licence to store and review this photograph and caption, send a private thumbnail in the venue review email, display it with my chosen credit on this venue’s BioVeracity page after approval, and download it for those purposes. I confirm I am 18 or over, have the necessary rights and permissions, and the image contains no identifiable children, private information or sensitive wildlife locations. Identifiable adults have agreed to the selected publication uses. I acknowledge the Privacy Notice. My private name and email are for rights administration, not marketing.'
export const RELEASE_VENUE = 'Optional: this named venue may use my photograph and caption with my credit in its future ecology publications: printed brochures, signs, newsletters, its own website and social channels, including promotion of this place.'
export const RELEASE_BIO = 'Optional: RippleXn may use my photograph and caption with my credit in future BioVeracity ecology publications: printed reports, books, brochures, exhibitions, newsletters, its website and social channels, including promotion of BioVeracity.'
export const RELEASE_LIMITS = 'These are worldwide, non-exclusive, royalty-free permissions for the selected uses. Reasonable cropping, resizing and colour correction are allowed, but not misleading edits, false species claims, implied personal endorsement, resale as stock or general-purpose AI training. Printers and service providers may process the image only to deliver the selected publication. You can withdraw permission for future use using your private receipt or Contact. We will stop new use and review controlled online copies; printed and previously distributed copies may not be recoverable. A separate lawful basis may justify limited rights records. Refusing optional uses does not prevent contribution. Subscription cancellation does not expand these permissions.'
export type ReleaseInput = {contactName:string;contactEmail:string;venuePublications:boolean;bioPublications:boolean;releaseVersion:string;releaseAccepted:true}
export function releaseInput(raw: unknown): ReleaseInput {
 const v=record(raw)
 if(v.releaseAccepted!==true||v.releaseVersion!==RELEASE_VERSION)throw new HubError(400,'Read and accept the current contributor release.')
 if(typeof v.contactName!=='string'||!v.contactName.trim()||v.contactName.length>160)throw new HubError(400,'Add your private contact name.')
 if(typeof v.contactEmail!=='string'||v.contactEmail.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.contactEmail))throw new HubError(400,'Add a valid private contact email.')
 if(typeof v.venuePublications!=='boolean'||typeof v.bioPublications!=='boolean')throw new HubError(400,'Choose each optional publication permission.')
 return {contactName:v.contactName.trim(),contactEmail:v.contactEmail.trim().toLowerCase(),venuePublications:v.venuePublications,bioPublications:v.bioPublications,releaseVersion:RELEASE_VERSION,releaseAccepted:true}
}
